name: Publish to NPM

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - run: npm install
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: Create GH Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            catppuccin-tailwindcss-*.tgz
          append_body: |
            NPM: https://www.npmjs.com/package/@catppuccin/tailwindcss/v/${{github.ref_name}}